var MyName = ("my name is mohammad ahmed")
alert (MyName)
var pizza = ("PIZZA\nPIZZ\nPIZ\nPI\nP")
alert (pizza)
var email = ("am9474036@gmail.com")
alert(email)
var FirstName = ("Ahmed")
var SecondName = ("Mehmood")
var fullName = (FirstName+SecondName)
alert(fullName)
var sign = ("“▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬”")
alert(sign)
